### PR TITLE
Pass getResolve to the worker pool

### LINKED ISSUE #79: Issue with `sass-loader` (this.getResolve is not a function)
Hey folks,

I've facing the following issue with `sass-loader`:
<details>
<summary><b>Error Details</b></summary><br>

```sh
ERROR in ./app.scss (./node_modules/thread-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./app.scss)
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
this.getResolve is not a function
    at PoolWorker.fromErrorObj (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at mapSeries (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/thread-loader/dist/WorkerPool.js:170:35)
    at readBuffer (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/thread-loader/dist/WorkerPool.js:152:14)
    at Object.loader (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/sass-loader/dist/index.js:52:26)
 @ ./app.scss 1:14-155
```

</details>

When I remove `thread-loader` from the loaders chain, it works correctly. Here is a very simple repo to reproduce that issue: https://github.com/ngryman/thread-sass-loaders-bug.

I've also already surfaced that issue in the `sass-loader` repo as I'm not sure which package is buggy.

### PR DESCRIPTION
**Pull request by ngryman**
Fixes #79.

cc @evilebottnawi

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Can we add simple test?

**Comment by ngryman** [comment]
@evilebottnawi It seems that it's less trivial than simply passing it as a prop 🤔

We would need to implement it here too I suppose: https://github.com/webpack-contrib/thread-loader/blob/master/src/WorkerPool.js#L191. Would you mind providing additional context / help for this? Thanks.

**Comment by evilebottnawi** [comment]
in todo, but i have very many tasks, 

> Would you mind providing additional context / help for this? Thanks.

you should create webpack configuration with `thread-loader` and for example `sass-loader` then run compilation and snapshot `stats.compilation.warnings/errors/assets` after build

**Comment by ngryman** [comment]
> @evilebottnawi in todo, but i have very many tasks

Yea I can imagine that this is not a top priority. My todo list is pretty crowded too unfortunately 😞 But I'm interested enough in that feature to allocate some time because it would help us migrating to use `sass-loader` instead of another, less maintained, loader.

I suspect this issue to be slightly more important than it seems because it probably affect other loaders than `sass-loader`. The [original issue](https://github.com/webpack-contrib/sass-loader/issues/761) seem to have landed on a workaround which is to downgrade `sass-loader` with increasing thumbs up for that workaround 👍 

---

> you should create webpack configuration with thread-loader and for example sass-loader then run compilation and snapshot stats.compilation.warnings/errors/assets after build

Thanks, that's what I've already done to highlight the issue: https://github.com/ngryman/thread-sass-loaders-bug.

I was more asking context about Webpack's internals and how to implement this thing I suppose. As I you're probably quite busy with other issues, I'll try to ask precise questions to help moving things foward:
1. What exactly `getResolve` does compared to `resolve`? IIRC I couldn't find proper documentation on it.
2. How would you suggest to implement it? As I understand it we can only pass strings between processes so I wonder how you would approach passing [a function that returns another function](https://github.com/webpack-contrib/sass-loader/blob/master/src/index.js#L43).

And thanks for your time 👍

**Comment by evilebottnawi** [comment]
> What exactly getResolve does compared to resolve? IIRC I couldn't find proper documentation on it.

Override/append/prepend resolve options, look here https://github.com/webpack-contrib/sass-loader/blob/master/src/index.js#L43

Let's look on this https://webpack.js.org/configuration/resolve/#resolveextensions, by default webpack  uses `['.wasm', '.mjs', '.js', '.json']`, but it is not good for `sass-loader`, because sass we should allow to resolve styles, so we use ` extensions: ['.scss', '.sass', '.css', '...'],`, so `webpack` uses extensions `['.scss', '.sass', '.css', '.wasm', '.mjs', '.js', '.json']` for `.sass`/`.scss`

It is shortly.

> How would you suggest to implement it? As I understand it we can only pass strings between processes so I wonder how you would approach passing a function that returns another function.

We already pass other functions like `emitError`/`resolve`/etc and all work fine, you implementation is correct, we just need add test for this and we can merge

**Comment by ngryman** [comment]
@evilebottnawi Thanks I appreciate the details.

Unless I'm missing something my current implementation does nothing, does it? 🤔 As I understand it I would need to add some code in the [worker](https://github.com/webpack-contrib/thread-loader/blob/master/src/worker.js#L102) and a case in [WorkerPool#onWorkerMessage](https://github.com/webpack-contrib/thread-loader/blob/master/src/WorkerPool.js#L145).

If that's the case, then `getResolve` is quite different from `emitError` or `resolve` as it returns another function, hence my question. As I can see how to serialize an object with the `WorkerPool#writeJson` method, I have more trouble with understanding how I could serialize a function.

Again if I've missed something along the road, please let me know. Thanks for your time on this.

**Comment by evilebottnawi** [comment]
Yes, it is invalid solution, we prepare the next major release with solved this problem, ETA is beginning of next month

**Pull request closed without merging**
