### PR TITLE
feat: add target, minimize and resourceQuery into context

### LINKED ISSUE #24: Get loader context in loader which is run in thread pool
@sokra 
We are using https://github.com/vuejs/vue-style-loader for loading `.vue` styles and trying to speed css loading up by using `thread-loader`.

But in `vue-style-loader`, it need to access properties in `loader context` like: [target](https://github.com/vuejs/vue-style-loader/blob/master/index.js#L14) and [resourcePath](https://github.com/vuejs/vue-style-loader/blob/master/index.js#L30).

If I understood correctly, `thread-loader` seems to run these loaders in a new context which doesn't include them, is there any way to get the properties ?

### PR DESCRIPTION
**Pull request by clarkdo**
Resolved #24

### CODE REVIEW

**Comment by clarkdo** [comment]
@sokra Can this be merge ?

**Comment by raejin** [comment]
@sokra Would love to see this being merged!

**Comment by sokra** [comment]
It can be merged. Cc @evilebottnawi

**Comment by clarkdo** [comment]
Thanks @evilebottnawi

**Comment by evilebottnawi** [comment]
@clarkdo it is feature, not bugfix?

**Comment by clarkdo** [comment]
@evilebottnawi Yes, it's a new feature with some new properties.

**Comment by evilebottnawi** [comment]
@clarkdo published

**Pull request merged**
