### PR TITLE
copy getOptions from webpack

### PR DESCRIPTION
**Pull request by qnighy**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Attempt to fix https://github.com/webpack-contrib/thread-loader/issues/106, a major compatibility problem with Webpack 5.

### Breaking Changes

No.

### Additional Info

Ideally we should be able to delegate computation to the main process, but unfortunately `getOptions` needs to return a value synchronously. In this PR I just copied the code verbatim. Copyright-wise, it should be sufficient to ask @alexander-akait and @sokra because they seem to be the only authors of the code.

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Ideally we should run webpack api here not copy this, because it can be bad for future webpack changes

**Comment by qnighy** [comment]
> Ideally we should run webpack api here not copy this, because it can be bad for future webpack changes

I agree with it, though as of 5.31.2 it's hard to call webpack's getOptions from workers because it's created in NormalModule.prototype.createLoaderContext.

Possible options:

- Keep the status quo in this PR.
- Expose `getOptions` implementation from webpack.
- Port webpack's `getOptions` back to schema-utils or loader-utils, and use it from both webpack and thread-loader.

**Comment by qnighy** [comment]
@alexander-akait here's another attempt: https://github.com/webpack/schema-utils/pull/123. Which do you think is better?

**Comment by sokra** [comment]
Seems fine to copy the implementation. I don't think we will change that in webpack any time soon (it would be a breaking change anyway).

**Pull request merged**
