### PR TITLE
fix(index): add `webpack >= v4.0.0` support

### LINKED ISSUE #14: webpack 4 Support
<h2 align="center"><a href="https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202">Official Migration Guide for Loaders/Plugins</a></h2>

### TODO

- [x] remove usages of `this.options.context` for  `this.rootContext` (https://github.com/webpack-contrib/thread-loader/blob/master/src/index.js#L21). `webpack >= v4.0.0` removed `this.options` from the Loader API and `this.options.context` is now exposed  as `this.rootContext`, which needs to be **added** to current implementation for `webpack` 4 support

 ~~- [x] update usage of `fileDependencies` && `contextDependencies` to reflect new data types. These are `{Set}`'s now instead of an `{Array}` (https://github.com/webpack-contrib/thread-loader/blob/master/src/index.js#L24-L25)~~

### First Contributors

 💁 If you're stuck or in doubt about something always feel free to ask question in the issue thread and/or by pinning one of the @webpack-contrib/org-maintainers

### PR DESCRIPTION
**Pull request by iansu**
### `Notable Changes`

Upgrade thread-loader to be compatible with webpack 4.

### `Issues`

- Closes #14

### CODE REVIEW

**Comment by andriijas** [comment]
@iansu thanks for taking care of this one!

**Comment by andriijas** [comment]
@michael-ciniawsky is the npm access resolved? looking foward to try it with webpack 4.

thanks

**Comment by michael-ciniawsky** [comment]
@andriijas Nope, unfortunately not 😞

**Comment by benthemonkey** [comment]
@iansu I published your change to `@benthemonkey/thread-loader` so I could start using it with webpack 4, in case anyone else wants to get unblocked.

Thanks for the fix!

**Comment by michael-ciniawsky** [comment]
Released in [`v1.1.4`](https://github.com/webpack-contrib/thread-loader/releases/tag/v1.1.4) 🎉  Sry for the delay here

**Comment by icxDave** [comment]
We seem to be getting:
````
Uncaught Error: Module build failed: Error: Cannot find module 'async/queue'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/stymie-ui/node_modules/thread-loader/dist/WorkerPool.js:15:14)
````
now as of a few hours ago...

**Comment by geirsagberg** [comment]
Great job :) Should probably add `^4.0.0 ` to peerDependencies then?

**Pull request merged**
